fix alert design close #31
ShopOne/Shitforces pull request #154
Opened 2021-04-04 13:20 UTC by ShopOne

alertのデザインを変更しました。

2021-04-04 22:44 UTC, rdrgn requested changes
Prettierによるフォーマットが走っていないように見えます。修正お願いします。

コミットすると自動で掛かるように設定したつもりでしたがHuskyの設定をちゃんとできていなそうですね……(๑>﹏<๑｀)

2021-04-05 14:42 UTC, ShopOne commented
本当ですね、適用されてなかったので手動での適用を行いました。
自動が上手く行ってないみたいですね…

2021-04-05 22:11 UTC, rdrgn commented on frontend/src/components/SubmitAccountInfo.tsx
> +  const auth = useAuthentication();
15行目でも`useAuthentication`を呼んでいるのでそちらと統合できます。
この行を削除して、15行目を次のように修正するのがよいと思います。

```ts
  const { accountName, signIn, signUp } = useAuthentication();
```

2021-04-06 08:15 UTC, ShopOne commented on frontend/src/components/SubmitAccountInfo.tsx
> +  const auth = useAuthentication();
本当ですね、ありがとうございます。(ライブ感でコーディングするとミスが出ますね…)
accountNameを使うようにしたのと、stateの方のaccountNameと名前が重複しちゃったのでstateの方の変数名を書き換えました。

2021-04-06 08:20 UTC, rdrgn approved these changes
🍡

2021-04-06 08:24 UTC, merged