Form key down
ShopOne/Shitforces pull request #181
Opened 2021-04-20 17:17 UTC by noyanyan

close #113
ContestPage.tsx
キー操作で提出することができるようになりました。
現在は、ctrl + enterで提出されるよう設定しています。

Package.json
eslintがなぜか入っていなかったので、入れました。docker起動時にwebpack依存のライブラリの自動ダウンロードができず、frontコンテナが落ちる挙動があったので、devに追加しています。

他ファイルは型定義追加などのリファクタリングです。

2021-04-20 17:19 UTC, noyanyan commented
次からはPRを小分けにします・・・(文脈が分散するとコードリーディングの負荷が大きそうなので)
すみませんがよろしくおねがいします！

2021-04-21 09:26 UTC, ShopOne requested changes
かなりの作業量有難うございます！  リファクタリングまでしていただいて助かります。
大分煩雑なコードになっていたと思います、すみません…
eslint入ってなかったんですね… いつのまに ありがとうございます。
いくつかの指摘事項を記入させていただいたので、そちらご確認とcommitの方をお願いしたいです。

2021-04-21 09:26 UTC, ShopOne commented on frontend/src/pages/ContestPage.tsx
>      // 最初の色つけタイミングのみこの様に処理する必要がある
今回のソースですと、 Rendered more hooks than during the previous render. のエラーが出てしまい、僕の環境では動きませんでした。
useEffect よりこのコードが前に居るため、`return <div/>`が成された場合に useEffect が実行されなかったのが原因と思われます。
ただ、今回の修正で、おそらくこちらの処理が無くても大丈夫になったと思うので、こちらの3行は消して頂けると助かります。

2021-04-21 09:26 UTC, ShopOne commented on frontend/src/pages/ContestPage.tsx
> +  key: string;
ここの Props の名前を key にしていますが、(よく原因わからないんですが)名前を key にすると key が undefined になってしまい、自分の提出を表示することが出来ませんでした。
なので tabKey 等に名前の改名をお願いしたいです。

2021-04-21 09:26 UTC, ShopOne commented on frontend/src/pages/ContestPage.tsx
> +        </Button>
(ちょっと記入の場所に困りましたが一応ここで)
ありがたくも、Ctrl + Enter で送信できるようにして頂けて嬉しいですが、このままだとその機能の追加に気がつけないと思うので、ボタンの横あたりに、 Ctrl + Enter で送信できるという旨を書いて頂けると嬉しいです。

2021-04-21 10:27 UTC, noyanyan commented on frontend/package.json
> +    "chokidar": "3.5.1",
自分も使われている確信はないですが、使われているのではないかと考えてます。
事実と推測をそれぞれ書きますね。

エラー
docker compose up でfrontendコンテナを起動すると、以下のエラーコードが発生します。
エラーログが(省略した部分で)指示するようにchokidarをマニュアルインストールすると、dockerコンテナは正常に起動するようになっています。
```
Error: No version of chokidar is available. Tried chokidar@2 and chokidar@3. frontend_1 | You could try to manually install any chokidar version.
```

調べてみると、chokidarはwebpackで使われているモジュールで、今回と同様のエラーをYoutubeで確認することができました。webpackの文字がエラーログに含まれていたように思うので、とりあえず入れています。
後でエラーを再現してみます。エラーログを実際に確認できたら、また報告します。

https://github.com/webpack/webpack/blob/a52263b4537dc5bd954677fc884966b0c11114d4/yarn.lock#L1688
https://www.youtube.com/watch?v=9UrEb1tbwgM

2021-04-21 10:29 UTC, noyanyan commented on frontend/src/pages/ContestPage.tsx
> +        </Button>
placeholderでフォームの部分に表示してみようと思います！

2021-04-22 12:50 UTC, noyanyan commented
1. hokidarを削除しました
再度エラーが出た場合に追加する形でよいかと思います。chokidarはreact-create-appのホットリロード機能に使われているはずなので、dockerでホットリロード関連が壊れたら関連を疑って良いと思います。
2. 誤ってコミットに追加していたプラグインを削除しました

2021-04-22 14:39 UTC, ShopOne approved these changes
大丈夫そうです、ありがとうございます！！！

2021-04-22 14:39 UTC, merged