順位表の時間表示を一部修正　
ShopOne/Shitforces pull request #182
Opened 2021-04-20 20:58 UTC by noyanyan

close #170
コンテストページ得点欄の時間表示のフォーマットを変えました。
コミットメッセージで間違えてますが、フォーマットは分分：秒秒ですね。中身は大丈夫です。

周辺の型定義を追加、コンポーネントを切り出しました。
reactはコンポーネントをなるべく小さく分けて、レイアウト（ビュー）部分とロジック部分を独立させることがベストプラクティスのようです。コンポーネントを細かく分けることはパフォーマンス戦略としても優れていますし、独立性を高めることはメンテの容易さにも繋がります。

@rdrgn PRのリファクタリング部分で#133の作業とコンフリクトしている部分があれば、ご自身のファイルの方を優先してくださって大丈夫です！コンフリクト解決は面倒だと思うので……

2021-04-21 01:53 UTC, rdrgn commented
> PRのリファクタリング部分で#133の作業とコンフリクトしている部分があれば、ご自身のファイルの方を優先してくださって大丈夫です！コンフリクト解決は面倒だと思うので……

お気遣いありがとうございます。問題の #133 は重すぎて半ばで放置しておりましたので、無視して大丈夫です。むしろリファクタリングを進めていただけてありがたいです。

2021-04-21 09:55 UTC, ShopOne commented on frontend/src/types/index.ts
> +// ユーザーの順位に関係するデータだとすぐわかるようにしたいです
こちらはそうですね… 全部Rankingでやってて分かりにくいですね。
今回の改修の範疇は超えてしまうので一旦commentだけで別にissueを建てますが、一応Accountで統一して名前を作っている(つもり) ですので、 AccountInfoOfStandings みたいになるかな？と思います。

2021-04-21 09:57 UTC, ShopOne commented on frontend/src/components/RankingTable.tsx
> +  // account.acceptListが(true|false)[]で与えられたら処理は簡単になる
これは本当にそうで、そのうち直します…

2021-04-21 09:57 UTC, noyanyan commented on frontend/src/types/index.ts
> +// ユーザーの順位に関係するデータだとすぐわかるようにしたいです
了解です！対応ありがとうございます！

2021-04-21 09:59 UTC, ShopOne requested changes
リファクタリングも含めて有難うございます！
いくつか指摘事項と補足コメントをさせていただいたので、ご確認のほど宜しくお願いします。

2021-04-21 09:59 UTC, ShopOne commented on frontend/src/components/RankingTable.tsx
> +        // 名前が衝突しています。動作が変わると嫌なのでとりあえずこのまま
こちらですが、おそらく下の i を変数名を変える(accountAcceptIdx等？)で同じ様に動作すると思うので変数名の変更お願いしたいです。

2021-04-21 09:59 UTC, ShopOne commented on frontend/src/components/RankingTable.tsx
> +  // isMe: boolean;
これらの使っていない変数のコメントアウトですが、使用していなければ消してしまって構わないので消去をお願いします。

2021-04-21 10:54 UTC, noyanyan commented on frontend/src/components/RankingTable.tsx
> +        // 名前が衝突しています。動作が変わると嫌なのでとりあえずこのまま
```{problems.map((problems)=> ... }```でproblemsが重複していることへのコメントでしたが、たしかに```i```も重複していますね。両方とも修正してみます。

2021-04-22 14:33 UTC, ShopOne requested changes
再度プルリクエストを出して頂きありがとうございます！
細かい所で申し訳ないのですが、再度指摘事項があるのでそちらの修正をお願いしたいです。
これが終われば merge 出来ると思います。

2021-04-22 14:33 UTC, ShopOne commented on frontend/src/components/RankingTable.tsx
> +    {/*  <td className={isMe ? 'table-info' : undefined}></td> */}
こちらも今の時点で使わなそうであれば、削除していただいて大丈夫です。

2021-04-22 14:33 UTC, ShopOne commented on frontend/src/components/RankingTable.tsx
> +  );
こちらも今の時点で使わなそうであれば、削除していただいて大丈夫です。

2021-04-22 14:33 UTC, ShopOne commented on frontend/src/components/RankingTable.tsx
> +const PlayerStatusOn_aProblem: React.VFC<PlayerStatusProps> = ({
クラス名についてなのですが、区切りの文字が大文字とアンダースコアで混在してしまっています。
下のに従って頂いて、パスカルケース(キャメルケースの先頭のみ大文字)でのクラス名にして頂きたいです。
それと status on もあまり聞かないので status of を使用して頂きたいです。
今回であれば、PlayerStatusOfProblem で良いです。 problems と problem があるので、 a を入れなくても一つか、一つでないかは区別は出来るので大丈夫です。
一つであることを明示的にしたい場合は、 PlayerStatusOfOneProblem 等も良いかなとも思います。
https://typescript-jp.gitbook.io/deep-dive/styleguide#%E3%82%AF%E3%83%A9%E3%82%B9

2021-04-22 15:30 UTC, noyanyan commented
丁寧なレビューありがとうございます。二度目の指摘は勇気がいりますが、受ける側としては率直に言ってもらえることでとてもやりやすく感じます。
（こちらからはreviewerを変更することができないので、 @ShopOne さんの負担が（雑務的な方向性で）増えそうなのを少し気にしています。）

PointAndAcTime関数はprobListでしか参照されないコンポーネントなので削除しました。

2021-04-23 02:40 UTC, ShopOne commented
こちらも内心ビクビクしながら Review を書いているので、そう行って頂けると精神的にとても助かります。ありがとうございます。
僕の作業量に関しては気にせず、どしどしプルリクエストを出してもらってOKです！ (忙しい時は反応遅れちゃうかもですが)
commit の内容については大丈夫そうです！ 再レビュー状態になっていないのでまだ merge は待機中です。
ついでのお願いですが、 conflict しているのを直して頂けると嬉しいです。(見た感じ probElement 消すだけっぽいですが)

2021-04-25 05:02 UTC, ShopOne approved these changes
大丈夫そうです、ありがとうございます！

2021-04-25 05:02 UTC, merged