[frontend] オートフォーカス追加/コンポーネント分割
ShopOne/Shitforces pull request #189
Opened 2021-04-26 06:27 UTC by noyanyan

close  #187
・タブが切り替わるたびに`<input/>`にフォーカスします。
・通信でProblemsを取得するまで、「コンテストが見つかりません」「エラー」と出る問題を修正しました
・軽微なバグを修正
・リファクタリング　＝＞コンポーネント分割（フォルダ構成は暫定策です）

 #133の文脈でコンポーネントの分割を少しやりました。これでもコンポーネントが最大100行程度あるので、もうすこし粒度を細かくしたいですが、このままだと少し難しそうです。

2021-04-26 06:33 UTC, noyanyan commented on frontend/src/components/RankingTable.tsx
> +  if (problems.length && problems.length !== ranking.acPerSubmit.length) {
最初のレンダリングの際、problemsは[]なのでデータをフェッチするまでErrorが表示されていましたが、見た目として良くなかったので修正しました。

2021-04-26 10:41 UTC, ShopOne requested changes
ありがとうございます！ 動作に関しては大丈夫そうです。
一点のみ関数名について細かいですが指摘がありますので、ご確認のほどよろしくお願いします。

2021-04-26 10:41 UTC, ShopOne commented on frontend/src/functions/getContestId.ts
> +  const splitPath = window.location.pathname.split('/');
こちらの getContestId ですが、この名前ですと何処からでも使えそうな名前になっています。
この場合 MainPage や ContestEditPage から呼び出したら、おかしな名前の contestId が返ってしまいます。
色々な所から呼び出すこと(とくに ContestEditPage) を想定するのなら、関数名を getContestIdOnContestRelatedPath 等に改名した上で、splitPath に 'contest' が含まれているかのバリデーションチェックをすると良いと思います。
実装としては、splitPath の中から、 contest の次の文字を取り出すようになると思います。

(RelatedPathは微妙かも？ いい表現が他にあればそれで)

2021-04-29 10:36 UTC, ShopOne approved these changes
大丈夫そうです！ありがとうございます。
コンフリについてはこっち側の変更なので、直しておきます。

2021-04-29 10:47 UTC, merged