improve Contest Page #114 #27 #243 #215
ShopOne/Shitforces pull request #250
Opened 2021-08-12 11:40 UTC by noyanyan

このPRは以下の内容からなります。
- 使っていないcssの除去
- contestページのコンポーネント分割・リファクタリング
- fetchのパフォーマンス改善

# fetchの高速化について
コンテストページは、これまで4つのfetchがそれぞれ完了するまでawaitしており、前のfetchが完了するまで次のfetchが始まりませんでした。

```
await fetchA()
await fetchB()
await fetchC()

// is the same as
fetchA().then(fetchB()).then(fetchC())...
```

`Promise.all()`を使うことでfetchを並列化しました。
書き方は[JavaScript Promiseの本](https://azu.github.io/promises-book/#ch2-promise-all)を参考にしています。

# Custom Hookについて
viewとlogicを分離することで、UIと機能を切り離します。
こうすると、UIの部分は確実に状態を持っていないので、どんなにいじっても安全だとわかり、開発しやすくなります。
https://sbfl.net/blog/2020/08/21/use-react-hooks-easy/

コミットごとにやることを分けたかったですが、重くて一気呵成にやるしかできなかったので、見辛いとおもいます。すみません。

2021-08-12 11:49 UTC, noyanyan commented on frontend/src/components/PagingElement.tsx
> +  ({ totalPages, currentPage, onChange, marginPx, savePaging }) => {
無駄な再レンダリングでサーバーへのリクエストが二重に飛んでいたので、メモ化して無駄なレンダリングをなくしました。

2021-08-12 11:52 UTC, noyanyan commented on frontend/src/pages/ContestPage/ContestStandingsTable.tsx
> +      event.preventDefault();
formでエンターを押すとsubmitされ画面を遷移しようとするので、これをやめさせました

2021-08-12 11:54 UTC, noyanyan commented on frontend/src/pages/ContestPage/ContestStandingsTableForRaid.tsx
> +                {createEnglishIndex(index)}
#215

2021-08-12 11:56 UTC, noyanyan commented on frontend/src/pages/ContestPage/index.tsx
> +      const [contestInfo, problems, submissions, accountInfo] = resources;
promise.allの部分で、唯一の大規模な書き直しです。

2021-08-14 02:35 UTC, noyanyan commented on frontend/src/types/index.ts
> +export type authority = authorities[keyof authorities];
https://qiita.com/uhyo/items/e2fdef2d3236b9bfe74a#lookup-types-tk

2021-08-14 15:20 UTC, ShopOne commented
ちょっと見るの遅れちゃいました 今日中にはなんとかレビューします

2021-08-15 10:14 UTC, ShopOne requested changes
動作とコードについては問題無さそうです、有難うございます！
前回気がつくべきだったんですが、一点だけ指摘事項がありますのでご確認のほどお願いします。

2021-08-15 10:14 UTC, ShopOne commented on frontend/package.json
> +    "fix": "run-s format lint-fix",
すみません、ここ前回気がついてなかったんですが、npm run fix をすると build/ 以下のコンパイル済みのコードまでフォーマットされてしまうので、src/ 下だけをfixするようにお願いしたいです。

2021-08-15 12:04 UTC, noyanyan commented on frontend/package.json
> +    "fix": "run-s format lint-fix",
気づきませんでした、ありがとうございます。

2021-08-16 14:40 UTC, ShopOne approved these changes
ありがとうございます！お疲れ様(?)でした。
すごく良くなっててとてもありがたいです。

2021-08-16 14:40 UTC, ShopOne commented on frontend/package.json
> +    "fix": "run-s format lint-fix",
ありがとうございます！

2021-08-16 14:40 UTC, merged