ページングの挙動をいろいろ変えた
ShopOne/Shitforces pull request #272
Opened 2021-12-12 11:18 UTC by stmtk1

- #263 をやりました
- #266 をやりました
- #148 をやりました
- window.historyではなくreact routerのuseHistoryをつかうようにしました
- アカウントのランキングのテーブルを別コンポーネントに切り出しました
-

2021-12-12 11:19 UTC, stmtk1 commented
![スクリーンショット 2021-12-12 20-18-39](https://user-images.githubusercontent.com/8833998/145710202-4511723a-96cc-4dee-b5e7-fa78c7028f2e.png)
![スクリーンショット 2021-12-12 20-18-56](https://user-images.githubusercontent.com/8833998/145710203-1cc37761-5387-44f3-b7f5-ccd41cb60f87.png)

2021-12-13 09:19 UTC, ShopOne requested changes
ありがとうございます！
一点だけ、ページを言って帰って来る所が上手く行っていないように思います。

メインページ コンテスト2ページ目を開く -> 2ページ目にあったコンテストを開く -> 戻るボタンを押す
の動作が行われた際に、メインページのコンテスト2ページ目が開かれていてほしいです。

2021-12-13 10:02 UTC, stmtk1 commented
そこの実装をしようとすると実装がかなり重くなると思うので、別イシューを立てていいですか？

2021-12-13 12:13 UTC, ShopOne commented
今はクエリパラメータを使わない実装になっていると思いますが、クエリパラメータを戻す実装にしても厳しいでしょうか？(ユーザー目線だと機能をそがれた形になるのであまり嬉しくなさそう)(誰も使ってない？)

2021-12-14 00:08 UTC, stmtk1 commented
使わない実装になってましたか。確認します

2021-12-14 04:29 UTC, stmtk1 commented
指摘された場所はきちんと動いてましたが、クリックしてもページが遷移しない実装になっていたので、それを修正しました。確認お願いします

2021-12-14 12:22 UTC, ShopOne commented
まだ部分的に動いていなさそうな気がします？
PagingElementでparams.get('page');をしていると思うんですが、たぶんこれを以下に書き換えるといい気がします。
`const paramPage = params.get('page') || '0'`;

あと、MainPageでかならずgetPastContestの0ページをセットしているのも良くなさそうで

```
 getPastContests(0).then((pastContestsInfo) => {
      setContestPageNum(
        Math.ceil(pastContestsInfo.allContestNum / CONTEST_IN_ONE_PAGE)
      );
    });
```
にすると動く気がします。 手元で軽く書いただけなのでちゃんと確認しただけですが…

2021-12-15 13:12 UTC, noyanyan commented
@ShopOne 
> まだ部分的に動いていなさそうな気がします？
どの部分の挙動が変わった/期待通りでないか、教えてもらえますか？
具体的な項目があると修正しやすいと思います。

2021-12-16 12:22 UTC, ShopOne commented
動作してほしい場合に動いてなかったのは以下の点です。
具体的な操作を書きますが、意味合いとしては伝わると思います。

- メインページの過去のコンテスト2ページ目をクリックし、次に名前をクリックして自分のページに移動、その後戻るボタンを押すとコンテストの2ページ目が開かれていてほしいが、1ページ目が開かれている(ページのボタンも2のまま)

2021-12-17 02:55 UTC, stmtk1 commented
修正しました

2021-12-18 12:07 UTC, ShopOne commented on frontend/src/pages/MainPage.tsx
>        })
たしかにページはこれで保存されてるんですが、これだと変わるのは過去のコンテストじゃなくてアカウントの順位表ですね…(草)
`getAccountRankingInfo(0)`のままで良くて、`getPastContest(page)`にすれば動くと思います！

2021-12-28 09:55 UTC, ShopOne approved these changes
大丈夫そうです、ありがとうございます！

2021-12-28 09:55 UTC, merged