バックエンドのライブラリのアップグレードをしました close #264
ShopOne/Shitforces pull request #273
Opened 2021-12-12 12:45 UTC by stmtk1

2021-12-13 09:29 UTC, ShopOne requested changes
ありがとうございます！
少しアプデ漏れがあるようですので、確認をお願いします。
IntelliJがあるといろいろ書いてくれますが、無ければこちらが参考になるかもしれません。
https://create-something.hatenadiary.jp/entry/2017/05/04/112749

2021-12-14 04:11 UTC, stmtk1 commented
試しにIntelliJをインストールしました。
特にアプデート漏れがないような表示が出ました。
入れるべきプラグインなどはありますか？

2021-12-14 12:29 UTC, ShopOne commented
おおっと、これはGradleの方のアップデートですかね？ 助かります。
それと一緒に、build.gradle.ktsの方を確認してみてもらうと、dependencies の implementation に入っている文字列が黄色の四角に囲まれていると思います。
そちらをアップデートしておきたいです。(もし見えない環境だったらすみません…)
![image](https://user-images.githubusercontent.com/47815703/145998538-ce2cdd17-c487-485b-b8bd-af9e2938446c.png)

2021-12-15 04:30 UTC, stmtk1 commented
バージョンが指定されてる部分に関してはアップグレード前に黄色く囲まれてたので修正しましたが、指定されてない部分に関しては黄色い背景は表示されませんでした。

2021-12-15 04:33 UTC, stmtk1 commented
spring bootのアップグレードができなかったので、gradle自身のアップグレードもついでにしておきました。
kotlint, spring dependency managementなどのpluginに関してもアップグレードが必要みたいですが、こちらは少々時間がかかりそうなので、少々お待ちください

2021-12-15 13:30 UTC, stmtk1 commented
おそらくライブラリのバージョンをきちんと指定すれば指摘された部分が治ると思うので、修正します

2021-12-15 14:06 UTC, stmtk1 commented
再びレビューお願いします

2021-12-16 12:27 UTC, ShopOne commented
死ぬほどタイミング悪く、今朝にlog4jのアップデートがあったみたいで、これをアップデートしないといけないんですが、これを繰り返しているとあんまりにも長引いてしまうので、いったんマージしてlog4jの方はこちらでアプデしておきます。
作業お疲れ様でした、ありがとうございます！

2021-12-16 12:28 UTC, ShopOne approved these changes

2021-12-16 12:29 UTC, ShopOne approved these changes

2021-12-16 12:29 UTC, merged